### ISSUE TITLE
Angajati adaugati dupa prima generare a programului

### ISSUE THREAD

**Issue by coisan** [WhatTheVlad/employee-scheduling#10]
4 zile, 3 angajati, nicio absenta, generam urmatorul program:
![image](https://user-images.githubusercontent.com/30983818/85233214-eb5f9480-b404-11ea-8568-dd2df94549c9.png)

Click pe "modific angajati", adaug al patrulea angajat, click pe "confirm angajati":
![image](https://user-images.githubusercontent.com/30983818/85233249-324d8a00-b405-11ea-960c-73aff643b245.png)

Regenerez programul, dar noul angajat nu este considerat in planificare:
![image](https://user-images.githubusercontent.com/30983818/85233252-3bd6f200-b405-11ea-97a6-386ac492a33f.png)

**Comment by WhatTheVlad** [comment]
Buna coisan,

Gandacul a fost corectat.

Multumesc pentru agerime,
WhatTheVlad
