### ISSUE TITLE
Dropdown alegere angajat pentru absente

### ISSUE THREAD

**Issue by coisan** [WhatTheVlad/employee-scheduling#11]
3 angajati, click pe "confirm angajati", dropdown-ul de alege angajat pentru a adauga absente contine cei 3 angajati:
![image](https://user-images.githubusercontent.com/30983818/85233366-ed762300-b405-11ea-97e8-4963b144cbb5.png)

Click pe "modific angajati", adaug al patrulea angajat, click pe "confirm angajati", iar dropdown-ul este:
![image](https://user-images.githubusercontent.com/30983818/85233400-21514880-b406-11ea-9ff6-fc47183fca17.png)

**Comment by coisan** [comment]
#5 - issue similar, nu se sterg valorile vechi din tabel / dropdown

**Comment by WhatTheVlad** [comment]
Buna coisan,

Gandacul a fost corectat.

Iti multumesc pentru perspicacitate,
WhatTheVlad
