### ISSUE TITLE
Regenerare tabela program

### ISSUE THREAD

**Issue by coisan** [WhatTheVlad/employee-scheduling#5]
4 zile, 2 angajati, nicio absenta, click pe "genereaza program":
![image](https://user-images.githubusercontent.com/30983818/85232303-4477fa00-b3fe-11ea-885b-a98c9532a9f4.png)

Daca dai click inca o data pe "genereaza program", se concateneaza coloane noi la cele vechi:
![Capture](https://user-images.githubusercontent.com/30983818/85232369-a9335480-b3fe-11ea-9f31-a38bdc826d57.PNG)

**Comment by WhatTheVlad** [comment]
Buna coisan,

Gandacul a fost exterminat si programul generat nu mai concateneaza coloanele vechi la cele noi.

Multumesc pentru ingenionzitate si spiritul critic,
WhatTheVlad
