### ISSUE TITLE
Numar ture incorect

### ISSUE THREAD

**Issue by coisan** [WhatTheVlad/employee-scheduling#6]
In cazul in care nu sunt suficienti angajati pentru a acoperi toate turele, numarul de ture al fiecarui angajat este incorect.

5 zile, 2 angajati, nicio absenta:
![image](https://user-images.githubusercontent.com/30983818/85232470-4d1d0000-b3ff-11ea-8632-8a4d93f9e1b9.png)
Conform programului, "andrei" si "vlad" au fiecare cate 3 ture, in loc de 5:
![image](https://user-images.githubusercontent.com/30983818/85232474-56a66800-b3ff-11ea-8c23-905f45a6a840.png)

**Comment by WhatTheVlad** [comment]
Buna coisan,

Acesta nu este un bug, intrucat tabelul angajati contorizeaza numarul total de ture necesare programului, impartit in mod egal la angajatii disponibili. "Total Ture" nu este cerut de client drept camp care sa reprezinte numarul de ture ramase, efectuate sau neacoperite.

Multumesc,
WhatTheVlad

**Comment by coisan** [comment]
mata
