### ISSUE TITLE
Modificare secventiala a datelor de intrare

### ISSUE THREAD

**Issue by coisan** [WhatTheVlad/employee-scheduling#7]
Datele de intrare pot fi introduse sau modificate doar in ordinea stricta: perioada -> angajati -> absente. Exista urmatoarele 2 cazuri:
1. confirm perioada -> confirm angajati -> confirm absente -> modific perioada -> confirm perioada => categoria absente are ambele butoane confirm / modific inactive

2. confirm perioada -> confirm angajati -> confirm absente -> modific perioada -> confirm perioada => butonul "modific angajati" este inactiv, se poate folosi doar "confirm angajati"

**Comment by WhatTheVlad** [comment]
Buna coisan, iti multumesc pentru observatiile pertinente.

1. Wizardul e conceput pentru a fi parcurs secvential. Utilizatorul nu ar trebui sa poata modifica absentele fara a confirma lista de angajati, intrucat pasul dedicat absentelor trebuie sa foloseasca cea mai recent actualizata lista de angajati.

2. Dupa "ultima" confirmare a perioadei, pasul dedicat listei de angajati devine activ si trebuie parcurs, iar ulterior, confirmat. Lista de angajati poate fi modificata doar atunci cand pasul dedicat acesteia este inactiv si utilizatorul se afla in alta portiune a wizardului (ex. modificare perioada, absente etc.).

Toate cele bune,
WhatTheVlad
