### ISSUE TITLE
Repartizare cu numar minim de ture neacoperite

### ISSUE THREAD

**Issue by coisan** [WhatTheVlad/employee-scheduling#8]
4 zile, 3 angajati, nicio absenta, rezulta urmatorul program cu **2 ture neacoperite**:
![image](https://user-images.githubusercontent.com/30983818/85232775-0250b780-b402-11ea-8039-c4f2314f2737.png)

O solutie mai eficienta cu **1 tura neacoperita**:
andrei, vlad
andrei, gigel
andrei, -
vlad, andrei

**Comment by WhatTheVlad** [comment]
Buna coisan,

Acesta nu este un bug intrucat angajatii trebuie sa respecte urmatoarele conditii:
- cei care lucreaza in tura de zi trebuie sa aiba urmatoarele 24h(2ture) libere.
- cei care lucreaza in tura de noapte trebuie sa aiba urmatoarele 48h(4ture) libere.

Comportamentul aplicatiei este cel asteptat si cerut de client.

Multumesc,
WhatTheVlad

**Comment by coisan** [comment]
mata
